[workspace]
authors = ["Sylens Wong <qiumin14@163.com>"]
channels = ["conda-forge"]
name = "theia"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
nodejs = ">=18.17.0,<21"
yarn = "*"
